import type { Metadata } from "next";

import "./globals.css";
import Menu from "@/components/Menu/Menu";
import { font_body, font_title } from "@/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(font_body);
  return (
    <html lang="pt-br">
      <body
        className={`${font_body.className} ${font_body.variable} ${font_title.variable}`}
      >
        <Menu />
        {children}
      </body>
    </html>
  );
}
